---
swagger: "2.0"
info:
  description: "\
    [solved.ac](https://solved.ac/) ì˜ ë¹„ê³µì‹ API ë¬¸ì„œì…ë‹ˆë‹¤. \
    ì›ì‘ìì˜ ìš”ì²­ì— ë”°ë¼ ì–¸ì œë“ ì§€ ì§€ì›Œì§ˆ ìˆ˜ ìˆìœ¼ë©°, \
    ë¬¸ì„œì˜ ë‚´ìš©ì€ í˜„ì¬ APIì™€ ì¼ì¹˜í•˜ì§€ ì•Šì„ ìˆ˜ ìˆìŠµë‹ˆë‹¤. \
    "
  version: "2020-06.1"
  title: "solved.ac"
  contact:
    email: "public.ranolp@gmail.com"
host: "api.solved.ac"
basePath: "/v2"
tags:
  - name: "ê¸°íƒ€"
    description: "ì•„ì§ ë¶„ë¥˜í•˜ì§€ ëª»í•œ APIì…ë‹ˆë‹¤"
  - name: "ì‚¬ìš©ì"
    description: "ì‚¬ìš©ìì™€ ê´€ë ¨ì´ ìˆëŠ” APIì…ë‹ˆë‹¤"
schemes:
  - "https"
paths:
  /search/recommendations.json:
    get:
      tags:
        - "ê¸°íƒ€"
      summary: "ì£¼ì–´ì§„ ì¿¼ë¦¬ì— ë”°ë¼ ë°±ì¤€ ë¬¸ì œë¥¼ ê²€ìƒ‰í•©ë‹ˆë‹¤."
      description: ""
      parameters:
        - name: "query"
          in: "query"
          description: "ì¿¼ë¦¬ ë¬¸ìì—´"
          required: true
          type: "string"
      responses:
        200:
          description: "ì„œë²„ê°€ ë°˜í™˜ì— ì„±ê³µí•œ ê²½ìš°ì…ë‹ˆë‹¤."
          schema:
            type: "object"
            properties:
              success:
                description: "ìš”ì²­ ì„±ê³µ ì—¬ë¶€ì…ë‹ˆë‹¤."
                type: "boolean"
                example: true
              result:
                type: "object"
                properties:
                  autocomplete:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                  problems:
                    description: "ê²€ìƒ‰í•´ì„œ ì°¾ì€ ë°±ì¤€ ë¬¸ì œ ëª©ë¡ì…ë‹ˆë‹¤."
                    type: "array"
                    items:
                      $ref: "#/definitions/Problem"
                  problem_count:
                    description: "ê²€ìƒ‰í•´ì„œ ì°¾ì€ ë°±ì¤€ ë¬¸ì œ ìˆ˜ì…ë‹ˆë‹¤."
                    type: "integer"
                    format: "int64"
                    example: 1
                  users:
                    description: "ê²€ìƒ‰í•´ì„œ ì°¾ì€ ì‚¬ìš©ì ëª©ë¡ì…ë‹ˆë‹¤."
                    type: "array"
                    items:
                      $ref: "#/definitions/User"
                  user_count:
                    description: "ê²€ìƒ‰í•´ì„œ ì°¾ì€ ì‚¬ìš©ì ìˆ˜ì…ë‹ˆë‹¤."
                    type: "integer"
                    format: "int64"
                    example: 1
                  algorithms:
                    description: "ê²€ìƒ‰í•´ì„œ ì°¾ì€ ì•Œê³ ë¦¬ì¦˜ ëª©ë¡ì…ë‹ˆë‹¤."
                    type: "array"
                    items:
                      $ref: "#/definitions/Algorithm"
                  algorithm_count:
                    description: "ê²€ìƒ‰í•´ì„œ ì°¾ì€ ì•Œê³ ë¦¬ì¦˜ ìˆ˜ì…ë‹ˆë‹¤."
                    type: "integer"
                    format: "int64"
                    example: 1
                  wiki_articles:
                    description: "ê²€ìƒ‰í•´ì„œ ì°¾ì€ ìœ„í‚¤ ê¸€ ëª©ë¡ì…ë‹ˆë‹¤."
                    type: "array"
                    items:
                      $ref: "#/definitions/WikiArticle"
  /site/statistics.json:
    get:
      tags:
        - "ê¸°íƒ€"
      summary: "solved.ac í†µê³„ë¥¼ ê°€ì ¸ì˜µë‹ˆë‹¤."
      description: ""
      responses:
        200:
          description: "ì„œë²„ê°€ ë°˜í™˜ì— ì„±ê³µí•œ ê²½ìš°ì…ë‹ˆë‹¤."
          schema:
            type: "object"
            properties:
              success:
                description: "ìš”ì²­ ì„±ê³µ ì—¬ë¶€ì…ë‹ˆë‹¤."
                type: "boolean"
              result:
                type: "object"
                properties:
                  total_problems:
                    description: "ì—¬íƒœê¹Œì§€ ìƒ‰ì¸ëœ ë°±ì¤€ ë¬¸ì œ ìˆ˜ì…ë‹ˆë‹¤."
                    type: "integer"
                    format: "int64"
                    example: 16355
                  voted_problems:
                    description: "ì—¬íƒœê¹Œì§€ íˆ¬í‘œëœ ë°±ì¤€ ë¬¸ì œ ìˆ˜ì…ë‹ˆë‹¤."
                    type: "integer"
                    format: "int64"
                    example: 9742
                  total_voters:
                    description: "ì—¬íƒœê¹Œì§€ íˆ¬í‘œí•œ ì‚¬ìš©ì ìˆ˜ì…ë‹ˆë‹¤."
                    type: "integer"
                    format: "int64"
                    example: 470
                  total_votes:
                    description: "ì—¬íƒœê¹Œì§€ ê¸°ë¡ëœ íˆ¬í‘œ ìˆ˜ì…ë‹ˆë‹¤."
                    type: "integer"
                    format: "int64"
                    example: 52085
  /users/problem_stats.json:
    get:
      tags:
        - "ì‚¬ìš©ì"
      summary: "ì‚¬ìš©ìê°€ í‘¼ ë¬¸ì œ ê°œìˆ˜ë¥¼ ë ˆë²¨ë³„ë¡œ ê°€ì ¸ì˜µë‹ˆë‹¤."
      description: ""
      parameters:
        - name: "id"
          in: "query"
          description: "ì‚¬ìš©ì ID"
          required: true
          type: "string"
      responses:
        200:
          description: "ì„œë²„ê°€ ë°˜í™˜ì— ì„±ê³µí•œ ê²½ìš°ì…ë‹ˆë‹¤."
          schema:
            type: "object"
            properties:
              success:
                description: "ìš”ì²­ ì„±ê³µ ì—¬ë¶€ì…ë‹ˆë‹¤."
                type: "boolean"
                example: true
              result:
                type: "array"
                items:
                  type: "object"
                  properties:
                    level:
                      description: "ë¬¸ì œì˜ ë ˆë²¨ì…ë‹ˆë‹¤."
                      type:
                        $ref: "#/definitions/Level"
                      example: 0
                    problems:
                      description: "solved.acì— ë“±ë¡ëœ ë¬¸ì œ ìˆ˜ì…ë‹ˆë‹¤."
                      type: "integer"
                      format: "int64"
                      example: 6456
                    solved:
                      description: "ì‚¬ìš©ìê°€ í‘¼ ë¬¸ì œ ìˆ˜ì…ë‹ˆë‹¤."
                      type: "integer"
                      format: "int64"
                      example: 105
                    attempted:
                      description: "ì‚¬ìš©ìê°€ ì‹œë„í•´ë³¸ ë¬¸ì œ ìˆ˜ì…ë‹ˆë‹¤."
                      type: "integer"
                      format: "int64"
                      example: 113
                    solved_exp_sum:
                      description: "ì‚¬ìš©ìê°€ í•´ë‹¹ ë ˆë²¨ì—ì„œ íšë“í•œ ê²½í—˜ì¹˜ì˜ í•©ì…ë‹ˆë‹¤."
                      type: "integer"
                      format: "int64"
                      example: 33600
definitions:
  Level:
    description: "Unratedë¶€í„° Ruby Iê¹Œì§€ë¥¼ 0 ~ 31ë¡œ í‘œí˜„í•˜ëŠ” ë ˆë²¨ì…ë‹ˆë‹¤."
    type: "integer"
    format: "int64"
  Problem:
    type: "object"
    properties:
      id:
        description: "ë¬¸ì œì˜ ê³ ìœ  ë²ˆí˜¸ì…ë‹ˆë‹¤."
        type: "integer"
        format: "int64"
        example: 8481
      title:
        description: "ë¬¸ì œì˜ ì œëª©ì…ë‹ˆë‹¤."
        type: "string"
        example: "Generator"
      level:
        description: "ë¬¸ì œì˜ ë‚œì´ë„ì…ë‹ˆë‹¤."
        type: "#/definitions/Level"
        format: "int64"
        example: 23
      solved:
        description: "ë¬¸ì œë¥¼ í‘¼ ì‚¬ëŒì˜ ìˆ˜ì…ë‹ˆë‹¤."
        type: "integer"
        format: "int64"
        example: 20
      caption:
        type: "string"
        example: "Generator"
      description:
        type: "string"
        example: "#8481"
      href:
        description: "ë¬¸ì œë¡œ ê°€ëŠ” í•˜ì´í¼ë§í¬ì…ë‹ˆë‹¤."
        type: "string"
        example: "https://www.acmicpc.net/problem/8481"
  User:
    type: "object"
    properties:
      user_id:
        description: "ì‚¬ìš©ìëª…ì…ë‹ˆë‹¤."
        type: "string"
        example: "shiftpsh"
      bio:
        description: "ì‚¬ìš©ìì˜ ìê¸°ì†Œê°œì…ë‹ˆë‹¤."
        type: "string"
        example: "ğŸ§¡ ì´ê³³ì˜ ê°œë°œìì…ë‹ˆë‹¤."
      profile_image_url:
        description: "ì‚¬ìš©ìì˜ í”„ë¡œí•„ ì‚¬ì§„ìœ¼ë¡œ ê°€ëŠ” í•˜ì´í¼ë§í¬ì…ë‹ˆë‹¤."
        type: "string"
        example: "https://static.solved.ac/uploads/profile/0565b63f0b204e990d1b163018a1c358992519b8.png"
      solved:
        description: "ì‚¬ìš©ìê°€ í‘¼ ë¬¸ì œ ìˆ˜ì…ë‹ˆë‹¤."
        type: "integer"
        format: "int64"
        example: 2412
      exp:
        description: "ì‚¬ìš©ìê°€ ì—¬íƒœê¹Œì§€ íšë“í•œ ê²½í—˜ì¹˜ëŸ‰ì…ë‹ˆë‹¤."
        type: "integer"
        format: "int64"
        example: 498605585
      level:
        description: "ì‚¬ìš©ìì˜ ë ˆë²¨ì…ë‹ˆë‹¤."
        type: "#/definitions/Level"
        example: 25
      class:
        description: "ì‚¬ìš©ìê°€ ì·¨ë“í•œ Classì…ë‹ˆë‹¤."
        type: "integer"
        format: "int64"
        example: 8
      class_decoration:
        description: "ì‚¬ìš©ìê°€ ì·¨ë“í•œ Classì˜ ìˆ˜ì¤€ì…ë‹ˆë‹¤."
        type: "integer"
        format: "int64"
        example: 0
      vote_count:
        description: "ì‚¬ìš©ìê°€ í•œ ë‚œì´ë„ íˆ¬í‘œì˜ ìˆ˜ì…ë‹ˆë‹¤."
        type: "integer"
        format: "int64"
        example: 1417
      rank:
        description: "ì‚¬ìš©ìì˜ solved.ac ìˆœìœ„ì…ë‹ˆë‹¤."
        type: "integer"
        format: "int64"
        example: 43
  Algorithm:
    type: "object"
    properties:
      tag_name:
        type: "string"
        example: "bitmask"
      full_name_en:
        type: "string"
        example: "Bitmask"
      full_name_ko:
        type: "string"
        example: "ë¹„íŠ¸ë§ˆìŠ¤í‚¹"
      problem_count:
        type: "integer"
        format: "int64"
        example: 150
      caption:
        type: "string"
        example: "tag:bitmask"
      description:
        type: "string"
        example: "150ë¬¸ì œ"
      href:
        type: "string"
        example: "/problems/tags/bitmask"
  WikiArticle:
    type: "object"
    properties:
      title:
        type: "string"
        example: "ì™„ì „ íƒìƒ‰"
      caption:
        type: "string"
        example: "ì™„ì „ íƒìƒ‰"
      description:
        type: "string"
        example: ""
      href:
        type: "string"
        example: "/wiki/w/ì™„ì „ íƒìƒ‰"
